services:
  postgres:
    image: postgres:latest
    container_name: tmp_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tmp
      POSTGRES_PASSWORD: passtmp
      POSTGRES_DB: tmp_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: